

import datetime
import numpy as np
import netCDF4 as nc
import sys
import re

flin0=sys.argv[1]
flin1=sys.argv[2]
flout=sys.argv[3]

data0 = nc.Dataset(flin0,"r")
t=np.asarray(data0["time"][:])
u=np.asarray(data0["uwnd"][:,:])
v=np.asarray(data0["vwnd"][:,:])
var=np.asarray(data0["ErrorVariance"][:,:])
x=np.asarray(data0["longitude"][:])
y=np.asarray(data0["latitude"][:])
e=np.asarray(data0["tri"][:,:])

nt=len(t)
nn=len(x)
ne=e.shape[0]

data1 = nc.Dataset(flin1,"r")
t1=np.asarray(data1["time"][:])
u1=np.asarray(data1["uwnd"][:,:])
v1=np.asarray(data1["vwnd"][:,:])
var1=np.asarray(data1["ErrorVariance"][:,:])

um1=u1[0,:]
ng1=np.where(um1**2>=0) #find points that are valid floats

for k in range(nt):
    j=np.where(t[k]==t1) # find common merge point in data
    j=j[0].tolist()
    if len(j)==1:
            print("j="+str(j)+" : k="+str(k))
            print(u.shape)
            print(u1.shape)
            print(var.shape)
            print(var1.shape)

            u[k,ng1]=u[k,ng1]+(var[k,ng1]/(var[k,ng1]+var1[j,ng1]))*(u1[j,ng1]-u[k,ng1])
            v[k,ng1]=v[k,ng1]+(var[k,ng1]/(var[k,ng1]+var1[j,ng1]))*(v1[j,ng1]-v[k,ng1])
            var[k,ng1]=var[k,ng1] * ( var1[j,ng1] / ( var[k,ng1]+var1[j,ng1] ) )

fill_value0=data0["uwnd"]._FillValue

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:
    ncout.createDimension('level' , 1)  
    ncout.createDimension('node' , nn)
    ncout.createDimension('element' , ne)
    ncout.createDimension('time', nt)
    ncout.createDimension('noel', 3)

    lon_var=ncout.createVariable('longitude', 'f8', ('node',))
    lon_var.units         = 'degree_east'
    lon_var.long_name     = 'longitude'
    lon_var.standard_name = 'longitude'
    lon_var.axis          = 'X'
    lon_var[:]=x[:]

    lat_var=ncout.createVariable('latitude', 'f8', ('node',))
    lat_var.units         = 'degree_north'
    lat_var.long_name     = 'latitude'
    lat_var.standard_name = 'latitude'
    lat_var.axis          = 'Y'
    lat_var[:]=y[:]

    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var.reference_time = 1777334400
    time_var.reference_date = '2026.04.28 00:00:00 UTC'
    time_var[:]=t[:]

    tri_var=ncout.createVariable('tri', 'i4', ('element','noel'))
    tri_var.long_name     = 'element list'
    tri_var.standard_name = 'element list'
    tri_var[:,:]=e

    u_var=ncout.createVariable('uwnd', 'f4', ('time','node'),fill_value    = fill_value0)
    u_var.long_name     = 'eastward_wind'
    u_var.units         = 'm/s'
    u_var.standard_name = 'eastward_wind'
    u_var.level = '10 m above ground'
    u_var[:,:]=u[:,:]

    v_var=ncout.createVariable('vwnd', 'f4', ('time','node'),fill_value    = fill_value0)
    v_var.long_name     = 'northward_wind'
    v_var.units         = 'm/s'
    v_var.standard_name = 'northward_wind'
    v_var.level = '10 m above ground'
    v_var[:,:]=v[:,:]

    vari_var=ncout.createVariable('ErrorVariance', 'f4', ('time','node'))
    vari_var.long_name     = 'error variance of wind estimate'
    vari_var.units         = 'm m / s / s'
    vari_var.standard_name = 'error variance of wind estimate'
    vari_var.level = '10 m above ground'
    vari_var[:,:]=var[:,:]

    ncout.close
