

import datetime
import numpy as np
import netCDF4 as nc
import sys
import re
import InterpNWPSUtility as nwps

mshfl="meshes/RWPS.V0a.msh"
xi, yi, ei = nwps.loadWW3Mesh(mshfl)
nn=len(xi)
xi=xi+360

flin=sys.argv[1]
flout=sys.argv[2]

data = nc.Dataset(flin,"r")
x1=np.asarray(data["longitude"][:])
#x1=x1-360 # shift grid to RWPS coordinates 
y1=np.asarray(data["latitude"][:])
t1=np.asarray(data["time"][:])
u1=np.asarray(data["UGRD_10maboveground"][:,:,:])
v1=np.asarray(data["VGRD_10maboveground"][:,:,:])

nt=len(t1)

u=np.zeros((nn,nt))
v=np.zeros((nn,nt))

from scipy.interpolate import RegularGridInterpolator

xu=np.max(x1)
yu=np.max(y1)
xl=np.min(x1)
yl=np.min(y1)

print("x min="+str(xl) + ", x max="+str(xu))
print("xi min="+str(np.min(xi)))
print("xi max="+str(np.max(xi)))
j=np.where( np.logical_and(   np.logical_and(xi>xl,xi<xu), np.logical_and(yi>yl,yi<yu) ) )
j=np.array(j).flatten()
xit=xi[j]
yit=yi[j]
print(j.shape)
print(u.shape)

print("start u interp")
uit=nwps.interpolate_curvilinear_to_pointsRRFS(x1,y1, np.transpose(u1), xit, yit)
#uit=nwps.interpolate_curvilinear_to_pointsRRFS(x1,y1, u1, xit, yit)
print("done u interp")
print("start v interp")
vit=nwps.interpolate_curvilinear_to_pointsRRSF(x1,y1, np.transpose(v1), xit, yit)
#vit=nwps.interpolate_curvilinear_to_pointsRRFS(x1,y1, v1, xit, yit)
print("done v interp")

u[j,:]=uit
v[j,:]=vit

print("uit")
print(uit)
print(uit.shape)

j=np.where(np.isnan(uit+vit))
fill_value0=-999999
uit[j]=fill_value0
vit[j]=fill_value0

#nn=len(xi)

MAPSTA=np.ones(nn, dtype=int)
print(ei.shape)
print(ei)
ne=ei.shape[0]

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('level' , 1)  
    ncout.createDimension('node' , nn)
    ncout.createDimension('element' , ne)
    ncout.createDimension('time', nt)
    ncout.createDimension('noel', 3)

    lon_var=ncout.createVariable('longitude', 'f8', ('node',))
    lon_var.units         = 'degree_east'
    lon_var.long_name     = 'longitude'
    lon_var.standard_name = 'longitude'
    lon_var.axis          = 'X'
    lon_var[:]=xi[:]

    lat_var=ncout.createVariable('latitude', 'f8', ('node',))
    lat_var.units         = 'degree_north'
    lat_var.long_name     = 'latitude'
    lat_var.standard_name = 'latitude'
    lat_var.axis          = 'Y'
    lat_var[:]=yi[:]

#    time_var=ncout.createVariable('time', 'f8', ('time',))
#    time_var.units         = 'days since 1990-01-01 00:00:00'
#    time_var.long_name     = 'julian day (UT)'
#    time_var.standard_name = 'time'
#    time_var.axis          = 'T'
#    time_var[:]=time[:]

    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var.reference_time = 1777334400
    time_var.reference_date = '2026.04.28 00:00:00 UTC'
    time_var[:]=t1[:]
#    time_var[:]=time[:]

    tri_var=ncout.createVariable('tri', 'i4', ('noel','element'))
    tri_var.long_name     = 'element list'
    tri_var.standard_name = 'element list'
    tri_var[:]=np.transpose(ei)

    map_var=ncout.createVariable('MAPSTA', 'i2', ('node',))
    map_var.units         = '1'
    map_var.long_name     = 'status map'
    map_var.standard_name = 'status map'
    map_var.axis          = 'node'
    map_var[:]=MAPSTA[:]

    u_var=ncout.createVariable('uwnd', 'f4', ('node','time'),fill_value    = fill_value0)
    u_var.long_name     = 'eastward_wind'
    u_var.units         = 'm/s'
    u_var.standard_name = 'eastward_wind'
    u_var.level = '10 m above ground'
#    u_var[:,:]=uit[:,:]
    u_var[:,:]=u[:,:]

    v_var=ncout.createVariable('vwnd', 'f4', ('node','time'),fill_value    = fill_value0)
    v_var.long_name     = 'northward_wind'
    v_var.units         = 'm/s'
    v_var.standard_name = 'northward_wind'
    v_var.level = '10 m above ground'
#    v_var[:,:]=vit[:,:]
    v_var[:,:]=v[:,:]

    ncout.close
