import os
import argparse
import numpy as np
import netCDF4 as nc
import sys
import math

from scipy.interpolate import interp1d

flin=sys.argv[1] 
flout=sys.argv[2] 

#might want to rewrite with an input file to derive full set of times
print("running InterpTimeNBM.py: takes a NBM forecast and resamples 3 hour")
print("time steps to 1 hour timesteps for the first 84 hours of the forecast")
print("to correspond with forecast times in rrfs")

data0 = nc.Dataset(flin,"r")

t=np.asarray(data0["time"][:])
u=np.asarray(data0["uwnd"][:,:])
v=np.asarray(data0["uwnd"][:,:])

x=np.asarray(data0["longitude"][:])
y=np.asarray(data0["latitude"][:])
d=np.asarray(data0["dist2bnd"][:])
e=np.asarray(data0["tri"][:,:])

#ensure we don't interpolate fill values
fill_value0 = data0["uwnd"]._FillValue
nan=float('nan')
jb=np.where(u==fill_value0)
u[jb]=nan
fill_value0 = data0["vwnd"]._FillValue
jb=np.where(v==fill_value0)
v[jb]=nan

nt0 =len(t)

ta = np.arange(t[0], t[28], 3600.)
#tb = t[range(29,nt0-1,1)]
tb = t[range(29,nt0,1)]

print("Initial times:")
print(t)

tf=np.hstack((ta,tb))
print("New times:")
print(tf)

nt=len(tf)
nn=len(x)
ne=e.shape[1]
noel=e.shape[0]

#set up interpolator for u
fi = interp1d(t, u.T, axis=0, kind='linear')
uf=fi(tf)

#set up interpolator for v
fi = interp1d(t, v.T, axis=0, kind='linear')
vf=fi(tf)
print(uf.shape)
print(u.shape)
#re-insert initial values at times that match initial time points
print("Interpolation compleate: now re-insert initial values at times that match initial time points")
print("to remove small interpolation artifacts")
for k in range(nt):
    j=np.where(tf[k]==t)
    j=j[0].tolist()
    print("new time index: "+str(k)+" is same as old time index:"+str(j))
    if len(j)>0:
        print("mapping exactly back to origonal values at time: "+str(tf[k]))
        j=j[0]
        uf[k,:]=u[:,j].T
        vf[k,:]=v[:,j].T

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('level' , 1)  
    ncout.createDimension('node' , nn)
    ncout.createDimension('element' , ne)
    ncout.createDimension('time', nt)
    ncout.createDimension('noel', 3)

    lon_var=ncout.createVariable('longitude', 'f8', ('node',))
    lon_var.units         = 'degree_east'
    lon_var.long_name     = 'longitude'
    lon_var.standard_name = 'longitude'
    lon_var.axis          = 'X'
    lon_var[:]=x[:]

    lat_var=ncout.createVariable('latitude', 'f8', ('node',))
    lat_var.units         = 'degree_north'
    lat_var.long_name     = 'latitude'
    lat_var.standard_name = 'latitude'
    lat_var.axis          = 'Y'
    lat_var[:]=y[:]

    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var.reference_time = 1777334400
    time_var.reference_date = '2026.04.28 00:00:00 UTC'
    time_var[:]=tf[:]

    tri_var=ncout.createVariable('tri', 'i4', ('noel','element'))
    tri_var.long_name     = 'element list'
    tri_var.standard_name = 'element list'
    tri_var[:]=e

    d_var=ncout.createVariable('dist2bnd', 'f4', ('node',))
    d_var.long_name     = 'distance to boundary'
    d_var.units         = 'km'
    d_var.standard_name = 'distance to boundary'
    d_var[:]=d[:]

    u_var=ncout.createVariable('uwnd', 'f4', ('node','time'),fill_value    = fill_value0)
    u_var.long_name     = 'eastward_wind'
    u_var.units         = 'm/s'
    u_var.standard_name = 'eastward_wind'
    u_var.level = '10 m above ground'
    u_var[:,:]=uf[:,:].T

    v_var=ncout.createVariable('vwnd', 'f4', ('node','time'),fill_value    = fill_value0)
    v_var.long_name     = 'northward_wind'
    v_var.units         = 'm/s'
    v_var.standard_name = 'northward_wind'
    v_var.level = '10 m above ground'
    v_var[:,:]=vf[:,:].T

    ncout.close
