

import datetime
import numpy as np
import netCDF4 as nc
import sys
import re
import InterpNWPSUtility as nwps

def QuickDistance(lat1, lon1, lats2, lons2):
    deg2kmY=111.
    deg2kmX=np.cos( np.pi * lat1 / 180.)*deg2kmY
    d= np.min(  np.sqrt( (  (lat1-lats2)*deg2kmY)**2 + ((lon1-lons2)*deg2kmX)**2 )  )
    return d
def QuickDistanceRegGrd(lat1, lon1, lats2, lons2):
    deg2kmY=111.
    deg2kmX = np.cos( np.pi * lat1 / 180.)*deg2kmY
    dlat = deg2kmY * np.min( [ np.abs( lat1-lats2[0]), np.abs( lat1-lats2[1])] ) 
    dlon = deg2kmX * np.min( [ np.abs( lon1-lons2[0]), np.abs( lon1-lons2[1])] ) 
    d = np.min([dlat,dlon])
    return d

mshfl="meshes/RWPS.V0a.msh"
xi, yi, ei = nwps.loadWW3Mesh(mshfl)
nn=len(xi)
xi=xi+360

flin=sys.argv[1]
flout=sys.argv[2]

data = nc.Dataset(flin,"r")
x1=np.asarray(data["longitude"][:])
y1=np.asarray(data["latitude"][:])
t1=np.asarray(data["time"][:])
u1=np.asarray(data["UGRD_10maboveground"][:,:,:])
v1=np.asarray(data["VGRD_10maboveground"][:,:,:])

nt=len(t1)
u=np.zeros((nn,nt))
v=np.zeros((nn,nt))

from scipy.interpolate import RegularGridInterpolator

#InterpNBMu = RegularGridInterpolator((x1, y1), np.transpose(u1), method='linear', bounds_error=False, fill_value=None)
#InterpNBMv = RegularGridInterpolator((x1, y1), np.transpose(v1), method='linear', bounds_error=False, fill_value=None)
InterpNBMu = RegularGridInterpolator((x1, y1), np.transpose(u1), method='linear', bounds_error=False)
InterpNBMv = RegularGridInterpolator((x1, y1), np.transpose(v1), method='linear', bounds_error=False)
uit=InterpNBMu((xi,yi))
vit=InterpNBMv((xi,yi))

print("uit")
print(uit)
print(uit.shape)

j=np.where(np.isnan(uit+vit))
fill_value0=-999999
uit[j]=fill_value0
vit[j]=fill_value0


##################################################################################
# Compute distance to boundary for each node in mesh:
# only needs to be done for nodes within interpolater
##################################################################################
nx=len(x1)
ny=len(y1)
#xb=np.hstack( (x1[0]+0*y1, x1        , x1[nx-1]+0*y1, x1            ) )
#yb=np.hstack( (y1        , y1[0]+0*x1, y1           , y1[ny-1]+0*x1 ) )

xb=[np.min(x1),np.max(x1)]
yb=[np.min(y1),np.max(y1)]
dist2bnd=np.zeros(nn)
for k in range(nn):
    dist2bnd[k]=QuickDistanceRegGrd(yi[k],xi[k],yb,xb)
    if k%10000==0:
        print(str(k)+":"+ str(nn)+":"+str(k/nn) )
        print(dist2bnd[k])

MAPSTA=np.ones(nn, dtype=int)
print(ei.shape)
print(ei)
ne=ei.shape[0]

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('level' , 1)  
    ncout.createDimension('node' , nn)
    ncout.createDimension('element' , ne)
    ncout.createDimension('time', nt)
    ncout.createDimension('noel', 3)

    lon_var=ncout.createVariable('longitude', 'f8', ('node',))
    lon_var.units         = 'degree_east'
    lon_var.long_name     = 'longitude'
    lon_var.standard_name = 'longitude'
    lon_var.axis          = 'X'
    lon_var[:]=xi[:]

    lat_var=ncout.createVariable('latitude', 'f8', ('node',))
    lat_var.units         = 'degree_north'
    lat_var.long_name     = 'latitude'
    lat_var.standard_name = 'latitude'
    lat_var.axis          = 'Y'
    lat_var[:]=yi[:]

#    time_var=ncout.createVariable('time', 'f8', ('time',))
#    time_var.units         = 'days since 1990-01-01 00:00:00'
#    time_var.long_name     = 'julian day (UT)'
#    time_var.standard_name = 'time'
#    time_var.axis          = 'T'
#    time_var[:]=time[:]

    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var.reference_time = 1777334400
    time_var.reference_date = '2026.04.28 00:00:00 UTC'
    time_var[:]=t1[:]
#    time_var[:]=time[:]

    tri_var=ncout.createVariable('tri', 'i4', ('noel','element'))
    tri_var.long_name     = 'element list'
    tri_var.standard_name = 'element list'
    tri_var[:]=np.transpose(ei)

    map_var=ncout.createVariable('MAPSTA', 'i2', ('node',))
    map_var.units         = '1'
    map_var.long_name     = 'status map'
    map_var.standard_name = 'status map'
    map_var.axis          = 'node'
    map_var[:]=MAPSTA[:]

    d_var=ncout.createVariable('dist2bnd', 'f4', ('node',))
    d_var.long_name     = 'distance to boundary'
    d_var.units         = 'km'
    d_var.standard_name = 'distance to boundary'
    d_var[:]=dist2bnd[:]

    u_var=ncout.createVariable('uwnd', 'f4', ('node','time'),fill_value    = fill_value0)
    u_var.long_name     = 'eastward_wind'
    u_var.units         = 'm/s'
    u_var.standard_name = 'eastward_wind'
    u_var.level = '10 m above ground'
    u_var[:,:]=uit[:,:]

    v_var=ncout.createVariable('vwnd', 'f4', ('node','time'),fill_value    = fill_value0)
    v_var.long_name     = 'northward_wind'
    v_var.units         = 'm/s'
    v_var.standard_name = 'northward_wind'
    v_var.level = '10 m above ground'
    v_var[:,:]=vit[:,:]

    ncout.close
