
import datetime
import numpy as np
import netCDF4 as nc
import sys
import re
import InterpNWPSUtility as nwps

import xarray as xr
import numpy as np
import xesmf as xe

flin=sys.argv[1]
flout=sys.argv[2]

mshfl="meshes/RWPS.V0a.msh"
xi, yi, ei = nwps.loadWW3Mesh(mshfl)
nn=len(xi)
xi=xi+360


#fl="rrfs/rrfs.t00z.2dfld.3km.na.10m.nc"
# 1. Load your RRFS data
# RRFS uses Lambert Conformal or curvilinear grids; xESMF handles these via 2D lat/lon arrays
ds_source = xr.open_dataset(flin)

# 2. Define target points (e.g., specific weather stations)
target_lats = yi
target_lons = xi

# Create a target dataset formatted for 'locstream'
ds_target = xr.Dataset(
    {
        "lat": (["locations"], target_lats),
        "lon": (["locations"], target_lons),
    }
)

# 3. Create the Regridder
# 'bilinear' is typically used for continuous variables like wind speed
# locstream_out=True tells xESMF to interpolate to the specific points in ds_target
regridder = xe.Regridder(
    ds_source, 
    ds_target, 
    method="bilinear", 
    locstream_out=True,
    unmapped_to_nan=True
)

# 4. Perform the interpolation
# If interpolating wind direction, convert to U/V components first to avoid angular issues
ds_interpolated = regridder(ds_source)

# Access the interpolated values (e.g., wind speed)
#print(ds_interpolated["wind_speed"].values)
#print(ds_interpolated["WIND_10maboveground"].values)

data = nc.Dataset(flin,"r")
t1=np.asarray(data["time"][:])

nn=len(xi)
nt=len(t1)

#nan=float('nan')
#u=np.zeros((nt,nn))+nan
#v=np.zeros((nt,nn))+nan

#u[:,:]=ds_interpolated["UGRD_10maboveground"].values
#v[:,:]=ds_interpolated["VGRD_10maboveground"].values
u=ds_interpolated["UGRD_10maboveground"].values
v=ds_interpolated["VGRD_10maboveground"].values

print(u.shape)
print(v.shape)
fill_value0=-99999
MAPSTA=np.ones(nn, dtype=int)
print(ei.shape)
print(ei)
ne=ei.shape[0]

with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:

    ncout.createDimension('level' , 1)  
    ncout.createDimension('node' , nn)
    ncout.createDimension('element' , ne)
    ncout.createDimension('time', nt)
    ncout.createDimension('noel', 3)

    lon_var=ncout.createVariable('longitude', 'f8', ('node',))
    lon_var.units         = 'degree_east'
    lon_var.long_name     = 'longitude'
    lon_var.standard_name = 'longitude'
    lon_var.axis          = 'X'
    lon_var[:]=xi[:]

    lat_var=ncout.createVariable('latitude', 'f8', ('node',))
    lat_var.units         = 'degree_north'
    lat_var.long_name     = 'latitude'
    lat_var.standard_name = 'latitude'
    lat_var.axis          = 'Y'
    lat_var[:]=yi[:]

    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'T'
    time_var.reference_time = 1777334400
    time_var.reference_date = '2026.04.28 00:00:00 UTC'
    time_var[:]=t1[:]
#    time_var[:]=time[:]

    tri_var=ncout.createVariable('tri', 'i4', ('noel','element'))
    tri_var.long_name     = 'element list'
    tri_var.standard_name = 'element list'
    tri_var[:]=np.transpose(ei)

    map_var=ncout.createVariable('MAPSTA', 'i2', ('node',))
    map_var.units         = '1'
    map_var.long_name     = 'status map'
    map_var.standard_name = 'status map'
    map_var.axis          = 'node'
    map_var[:]=MAPSTA[:]

    u_var=ncout.createVariable('uwnd', 'f4', ('node','time'),fill_value    = fill_value0)
    u_var.long_name     = 'eastward_wind'
    u_var.units         = 'm/s'
    u_var.standard_name = 'eastward_wind'
    u_var.level = '10 m above ground'
    u_var[:,:]=np.transpose(u[:,:])

    v_var=ncout.createVariable('vwnd', 'f4', ('node','time'),fill_value    = fill_value0)
    v_var.long_name     = 'northward_wind'
    v_var.units         = 'm/s'
    v_var.standard_name = 'northward_wind'
    v_var.level = '10 m above ground'
    v_var[:,:]=np.transpose(v[:,:])

    ncout.close
