#!/bin/bash
#SBATCH --job-name=jigsaw_py_RWPSng     # Job name
#SBATCH --mail-type=END             # Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=keston.smith@noaa.gov  # Where to send mail
#SBATCH --mem-per-cpu=256000mb         # Memory per processor
#SBATCH --time=00:29:00             # Time limit hrs:min:sec
#SBATCH --output=mpi_test_%j.log    # Standard output/error
##SBATCH --exclusive=user
#SBATCH --error=%j.err
##SBATCH --partition=marine-cpu
##SBATCH --account=marine-cpu
#SBATCH -q debug
#SBATCH --nodes=1
#SBATCH --ntasks=1



#module purge
#module use  /scratch3/NCEPDEV/climate/Keston.Smith/global-workflowA/sorc/ufs_model.fd/modulefiles/
#module load ufs_ursa.intel
#module load stack-oneapi/2024.2.1
#module load  python/3.11
#module load cmake/3.27.9

#module load py-numpy/1.26.4
#module load ufs_ursa.intel
#module load py-netcdf4/1.7.1.post2

source /scratch3/NCEPDEV/climate/Keston.Smith/UrsaMeshgenEnv3/jigsawenv/bin/activate
pip list -v

#InterpNBM.py  InterpNWPS.py  InterpNWPSUtility.py  MakeNBMWind.py  MakeNWPSWind.py  MergeNWPSWinds.py  SpdDir2UVnbm.py
python3 SpdDir2UVnbm.py forecast/nbm.20260428.00.wind10m.oc.nc nbm.UV.nc
python3 InterpNBM.py nbm.UV.nc nbm.RWPS.nc



#python3 SpdDir2UVnbm.py forecast/nbm.20260428.00.wind10m.oc.nc test.nc
#python3 MakeNBMWind.py test.nc testInterp.nc

##python3 RWPSMeshGenScript.py > NonGlobalMeshGen.out
##python3 RWPSMeshGenScript.GSHHS.py >  RWPSMeshGenScript.GSHHS.out
##python3 RWPSMeshGenScript.GSSHSxOSM.NewOrleans.py > RWPSMeshGenScript.GSSHSxOSM.NewOrleans.out
##python3 RWPSMeshGenScript.NWcoastal.py > RWPSMeshGenScript.NWcoastal.out
