#!/bin/bash
#SBATCH --job-name=jigsaw_py_RWPSng     # Job name
#SBATCH --mail-type=END             # Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=keston.smith@noaa.gov  # Where to send mail
#SBATCH --mem-per-cpu=256000mb         # Memory per processor
#SBATCH --time=00:29:00             # Time limit hrs:min:sec
#SBATCH --output=mpi_test_%j.log    # Standard output/error
##SBATCH --exclusive=user
#SBATCH --error=%j.err
##SBATCH --partition=marine-cpu
##SBATCH --account=marine-cpu
#SBATCH -q debug
#SBATCH --nodes=1
#SBATCH --ntasks=1



#module purge
#module use  /scratch3/NCEPDEV/climate/Keston.Smith/global-workflowA/sorc/ufs_model.fd/modulefiles/
#module load ufs_ursa.intel
#module load stack-oneapi/2024.2.1
#module load  python/3.11
#module load cmake/3.27.9

#module load py-numpy/1.26.4
#module load ufs_ursa.intel
#module load py-netcdf4/1.7.1.post2

source /scratch3/NCEPDEV/climate/Keston.Smith/UrsaMeshgenEnv3/jigsawenv/bin/activate
pip list -v

#forecast/nbm.20260428.00.wind10m.oc.nc
#forecast/rrfs.20260428.00.wnd10m.ak.nc
#forecast/rrfs.20260428.00.wnd10m.hi.nc
#forecast/rrfs.20260428.00.wnd10m.na.nc
#forecast/rrfs.20260428.00.wnd10m.pr.nc
#forecast/rrfs.20260428.c00.wnd10m.pr.nc

#InterpNBM.py   InterpNWPSUtility.py  InterpRRFS.py     MakeNBMWind.py	MergeNWPSWinds.py
#InterpNWPS.py  InterpRRFS.crvln.py   InterpRRFS.rg.py  MakeNWPSWind.py	SpdDir2UVnbm.py

#python3 InterpRRFS.rg.py forecast/rrfs.20260428.00.wnd10m.pr.nc RWPS.rrfs.20260428.00.wnd10m.pr.nc
#python3 InterpRRFS.rg.py forecast/rrfs.20260428.00.wnd10m.hi.nc RWPS.rrfs.20260428.00.wnd10m.hi.nc
python3 InterpRRFS.crvln.py forecast/rrfs.20260428.00.wnd10m.na.nc RWPS.rrfs.20260428.00.wnd10m.na.nc
python3 InterpRRFS.crvln.py forecast/rrfs.20260428.00.wnd10m.ak.nc RWPS.rrfs.20260428.00.wnd10m.ak.nc

python3 SpdDir2UVnbm.py forecast/nbm.20260428.00.wind10m.oc.nc nbm.UV.tmp.nc
python3 InterpNBM.py nbm.UV.tmp.nc RWPS.nbm.20260428.00.wind10m.oc.nc

