#module load ufs_ursa.intel 
#module load py-scipy/1.14.1 
#module load py-netcdf4/1.7.1.post2 
#python3 ../MakeNWPSWind.py ajk_202501010113_WIND.nc ajk_202501010113_WIND.WW3.nc

#import os
#import argparse
import numpy as np
import netCDF4 as nc
import sys

#import math
import datetime
first_date = datetime.datetime(1970, 1, 1)
time_since = datetime.datetime.now() - first_date

flin=sys.argv[1]
flout=sys.argv[2]

knts2mps=1./1.94384001

#ajk_202501010113_WIND.nc
stx="ajk_202501010113_WIND.nc"

print("y="+flin[4:8])
print("m="+flin[8:10])
print("d="+flin[10:12])
print("h="+flin[12:14])
print("m="+flin[14:16])

year=int(flin[4:8])
month=int(flin[8:10])
day=int(flin[11:12])
hour=int(flin[12:14])
mi=int(flin[14:16])

t0 = datetime.datetime(year, month, day, hour, mi)
tr = datetime.datetime(1970, 1, 1)
time_since = t0 - tr
sec0 = int(time_since.total_seconds())

print("year="+str(year))
print("month="+str(month))
print("day="+str(day))
print("hour="+str(hour))
print("min="+str(mi))

data0 = nc.Dataset(flin,"r")
x=np.asarray(data0["longitude"][:,:])
y=np.asarray(data0["latitude"][:,:])
spdkts=np.asarray(data0["Wind_Mag_SFC"][:,:,:])
theta =np.asarray(data0["Wind_Dir_SFC"][:,:,:])

spd=spdkts*knts2mps

spdV=data0["Wind_Mag_SFC"]
fill_value0 = spdV.fillValue

print("fil val")
print("spd shape")
print(spd.shape)

u=-1*spd*np.sin(theta*np.pi/180.)
v=-1*spd*np.cos(theta*np.pi/180.)
u[np.where(spd==fill_value0)]=fill_value0
v[np.where(spd==fill_value0)]=fill_value0

print(y.shape)
nx=x.shape[0]
ny=x.shape[1]
A=spd.shape;
nt=A[0]
t=np.zeros(nt)
print("time shape")
print(t.shape)
for k in range(nt):
    t[k]=float(sec0) + float(k)*3600.
print(t)


with nc.Dataset(flout, 'w', format='NETCDF4') as ncout:
        # Create dimensions
    ncout.createDimension('longitude' , nx)  
    ncout.createDimension('latitude' , ny)
    ncout.createDimension('time', nt)

    lon_var=ncout.createVariable('longitude', 'f8', ('longitude','latitude'))
    lon_var.units         = 'degree_east'
    lon_var.long_name     = 'longitude'
    lon_var.standard_name = 'longitude'
    lon_var.axis          = 'longitude'
    lon_var[:,:]=x[:,:]

    lat_var=ncout.createVariable('latitude', 'f8', ('longitude','latitude',))
    lat_var.units         = 'degree_north'
    lat_var.long_name     = 'latitude'
    lat_var.standard_name = 'latitude'
    lat_var.axis          = 'latitude'
    lat_var[:]=y[:]

    time_var=ncout.createVariable('time', 'f8', ('time',))
    time_var.units         = 'seconds since 1970-01-01 00:00:00.0 0:00'
    time_var.long_name     = 'verification time generated by wgrib2 function verftime()'
    time_var.standard_name = 'time'
    time_var.axis          = 'time'
    time_var[:]=t[:]

    u_var=ncout.createVariable('UGRD_10maboveground', 'f4', ('time','longitude','latitude'),fill_value    = fill_value0)
    u_var.long_name     = 'U-Component of Wind'
    u_var.units         = 'm/s'
    u_var.standard_name = 'UGRD_10maboveground'
    u_var.level = '10 m above ground'
    u_var[:,:,:]=u[:,:,:]

    v_var=ncout.createVariable('VGRD_10maboveground', 'f4', ('time','longitude','latitude'),fill_value    = fill_value0)
    v_var.long_name     = 'V-Component of Wind'
    v_var.units         = 'm/s'
    v_var.standard_name = 'VGRD_10maboveground'
    v_var.level = '10 m above ground'
    v_var[:,:,:]=v[:,:,:]

    ncout.close
